

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."delegates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" NOT NULL,
    "school" "text",
    "email" "text" NOT NULL,
    "phone" "text",
    "nationality" "text",
    "dob" "date",
    "type" "text",
    "accommodation" "text",
    "mun_experiences" "text",
    "referral_code" "text",
    "council1" "text",
    "council1_country" "text",
    "council2" "text",
    "council2_country" "text",
    "council3" "text",
    "council3_country" "text",
    "payment_proof_url" "text",
    "social_media_proof_url" "text",
    "id_proof_url" "text",
    CONSTRAINT "delegates_accommodation_check" CHECK (("accommodation" = ANY (ARRAY['yes'::"text", 'no'::"text"]))),
    CONSTRAINT "delegates_type_check" CHECK (("type" = ANY (ARRAY['Local'::"text", 'International'::"text"])))
);


ALTER TABLE "public"."delegates" OWNER TO "postgres";


ALTER TABLE "public"."delegates" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."delegates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."delegation_delegates" (
    "id" bigint NOT NULL,
    "delegation_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "delegate_order" integer NOT NULL,
    "name" "text" NOT NULL,
    "email" character varying NOT NULL,
    "phone_number" character varying NOT NULL,
    "nationality" "text" NOT NULL,
    "is_international_delegate" boolean NOT NULL,
    "mun_experiences" "text",
    "accommodation" "text" NOT NULL,
    "council_1" "text",
    "first_country_1" "text",
    "second_country_1" "text",
    "council_2" "text",
    "first_country_2" "text",
    "second_country_2" "text",
    "council_3" "text",
    "first_country_3" "text",
    "second_country_3" "text",
    "co_delegate_name_unsc" "text",
    "co_delegate_contact_unsc" "text",
    "social_media_proof_url" "text" NOT NULL,
    CONSTRAINT "delegation_delegates_delegate_order_check" CHECK ((("delegate_order" >= 1) AND ("delegate_order" <= 10)))
);


ALTER TABLE "public"."delegation_delegates" OWNER TO "postgres";


ALTER TABLE "public"."delegation_delegates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."delegation_delegates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."delegations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "delegation_name" "text" NOT NULL,
    "school" "text" NOT NULL,
    "head_delegate_name" "text" NOT NULL,
    "head_delegate_email" "text" NOT NULL,
    "head_delegate_phone" "text" NOT NULL,
    "payment_proof_url" "text",
    "referal_code" "text"
);


ALTER TABLE "public"."delegations" OWNER TO "postgres";


ALTER TABLE "public"."delegations" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."delegations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."observers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" NOT NULL,
    "nationality" "text",
    "mun_experiences" "text",
    "email" "text",
    "phone" "text",
    "payment_proof_url" "text",
    "council1" "text",
    "council2" "text",
    "council3" "text"
);


ALTER TABLE "public"."observers" OWNER TO "postgres";


ALTER TABLE "public"."observers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."observers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."delegates"
    ADD CONSTRAINT "delegates_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."delegates"
    ADD CONSTRAINT "delegates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."delegation_delegates"
    ADD CONSTRAINT "delegation_delegates_delegation_id_delegate_order_key" UNIQUE ("delegation_id", "delegate_order");



ALTER TABLE ONLY "public"."delegation_delegates"
    ADD CONSTRAINT "delegation_delegates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."delegations"
    ADD CONSTRAINT "delegations_head_delegate_email_key" UNIQUE ("head_delegate_email");



ALTER TABLE ONLY "public"."delegations"
    ADD CONSTRAINT "delegations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."observers"
    ADD CONSTRAINT "observers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."delegation_delegates"
    ADD CONSTRAINT "delegation_delegates_delegation_id_fkey" FOREIGN KEY ("delegation_id") REFERENCES "public"."delegations"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT USAGE ON SCHEMA "public" TO "data_team";








































































































































































GRANT ALL ON TABLE "public"."delegates" TO "anon";
GRANT ALL ON TABLE "public"."delegates" TO "authenticated";
GRANT ALL ON TABLE "public"."delegates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."delegates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."delegates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."delegates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."delegation_delegates" TO "anon";
GRANT ALL ON TABLE "public"."delegation_delegates" TO "authenticated";
GRANT ALL ON TABLE "public"."delegation_delegates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."delegation_delegates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."delegation_delegates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."delegation_delegates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."delegations" TO "anon";
GRANT ALL ON TABLE "public"."delegations" TO "authenticated";
GRANT ALL ON TABLE "public"."delegations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."delegations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."delegations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."delegations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."observers" TO "anon";
GRANT ALL ON TABLE "public"."observers" TO "authenticated";
GRANT ALL ON TABLE "public"."observers" TO "service_role";
GRANT SELECT ON TABLE "public"."observers" TO "data_team";



GRANT ALL ON SEQUENCE "public"."observers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."observers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."observers_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
