name: supabaseBackup

on:
  workflow_dispatch: #enable manual trigger
  schedule:
    # everyday at 00:00
    - cron: '0 0 * * *'

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Create timestamp folder
        run: mkdir -p prisma/backups

      - name: Backup roles
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/roles.sql --role-only

      - name: Backup schema
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/schema.sql

      - name: Backup data
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/data.sql --data-only --use-copy

      - name: Commit backups
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Supabase backup
